name: Clippy Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --no-default-features --features with_reqwest,prometheus_crate -- -D warnings
      - name: Run Clippy
        run: cargo clippy --no-default-features --features with_reqwest,prometheus_client_crate -- -D warnings
      - name: Run Clippy
        run: cargo clippy --no-default-features --features with_reqwest_blocking,prometheus_crate -- -D warnings
      - name: Run Clippy
        run: cargo clippy --no-default-features --features with_reqwest_blocking,prometheus_client_crate -- -D warnings

