name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --no-default-features --features with_reqwest,prometheus_crate
    - name: Run tests
      run: cargo test --verbose --no-default-features --features with_reqwest,prometheus_crate

    - name: Build
      run: cargo build --verbose --no-default-features --features with_reqwest,prometheus_client_crate
    - name: Run tests
      run: cargo test --verbose --no-default-features --features with_reqwest,prometheus_client_crate

    - name: Build
      run: cargo build --verbose --no-default-features --features with_reqwest_blocking,prometheus_crate
    - name: Run tests
      run: cargo test --verbose --no-default-features --features with_reqwest_blocking,prometheus_crate


    - name: Build
      run: cargo build --verbose --no-default-features --features with_reqwest_blocking,prometheus_client_crate
    - name: Run tests
      run: cargo test --verbose --no-default-features --features with_reqwest_blocking,prometheus_client_crate

